# Base Image
FROM ruby:2.3

# Encoding
# C.UTF8 locale supports Computer English language
ENV LANG C.UTF-8

# Default user and group id. This is important to avoid permission errors.
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apt-get update -qq && \
  apt-get install -y curl          \
  libpq-dev     \
  libxml2-dev   \
  libgmp-dev    \
  libxslt1-dev  \
  imagemagick   \
  libssl1.0-dev \
  git           \
  sudo          \
  ssh           \
  rsync         \
  procps        \
  vim

# --------------------------
# INSTALL NODEJS BY NVM
# --------------------------
ARG NODE_VERSION=12.16.3
ARG NVM_DIR=/usr/local/nvm

RUN mkdir $NVM_DIR && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN node -v
RUN npm -v
# --------------------------
# end NODEJS
# --------------------------

ENV APP_NAME farma
ENV _USER devel
ENV HOME /home/${_USER}
ENV APP /var/www/${APP_NAME}
ENV BUNDLE_PATH /bundle/vendor

RUN addgroup --gid $GROUP_ID ${_USER}
RUN adduser  --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID ${_USER} \
  && usermod -a -G sudo ${_USER} \
  && usermod -a -G staff ${_USER} \
  && echo "${_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
  && echo "${_USER}:${_USER}" | chpasswd

RUN mkdir -p $HOME \
  && mkdir -p $APP \
  && mkdir -p $BUNDLE_PATH \
  && chown -R ${_USER}:${_USER} $HOME \
  && chown -R ${_USER}:${_USER} $BUNDLE_PATH \
  && chown -R ${_USER}:${_USER} $APP

USER ${_USER}:${_USER}

WORKDIR $APP

RUN gem install bundler -v 1.7.6 \
  && gem install rack -v 2.1.4.1 \
  && gem install rack-cache -v 1.9.0 \
  && gem install rails -v 3.2.12

COPY --chown=${_USER}:${_USER} Gemfile Gemfile.lock ./
RUN bundle install --deployment --without development test

COPY --chown=${_USER}:${_USER} . .

EXPOSE 3000

CMD ["bash", "-lc", "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"]
