version: '3.8'
x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/var/www/farma
    - bundle_path:/bundle
  tmpfs:
    - /tmp
  depends_on:
    - db
  networks:
    - app-network
  stdin_open: true
  tty: true

services:
  web:
    <<: *app
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
        " # Removing server.pid is technically a cleanup script
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
    depends_on:
      - db

  db:
    image: mongo:4.4.6
    ports:
      - 27888:27017
    volumes:
      - mongodata:/data/db/
    networks:
      - app-network

volumes:
  mongodata:
    driver: local
  bundle_path:

networks:
  app-network:
    driver: bridge
