host:
  production: 'farma.educacional.mat.br'
  development: 'localhost:3000'
email:
  account: "farma.ufpr@gmail.com"
  passwd: "farma123"

experiment:
  control_group: ["53e9fa9f759b743c2d00002f"]
  access_group: ["53e9fa9f759b743c2d00002f"]
