host:
  production: "farma-calc.educacional.mat.br"
  development: "localhost:3000"

experiment:
  control_group: ["53e9fa9f759b743c2d00002f"]
  access_group: []

email:
  account: "alexs@professores.utfpr.edu.br"
