# set these environment variables on your prod server
production:
  sessions:
    default:
      database: <%= ENV.fetch("MONGODB_DATABASE", "farma_production") %>
      hosts:
        - <%= ENV.fetch("MONGODB_HOST", "db") %>
      options:
        consistency: :strong
